# Generated by Django 6.0.6 on 2026-07-04 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
